trivy-toolkit-backup:
  extends: .trivy-template
  variables:
    IMAGE_PROJECT_NAME: "terminus7/toolkit-backup"
    PROJECT_PATH: "toolkit-backup"
    CONTAINER_SCANNING_REPORT: gl-container-scanning-report-toolkit-backup.json
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report-toolkit-backup.json
  only:
    refs:
      - master
    changes:
      - toolkit-backup/**/*

release-toolkit-backup-image:
  stage: semantic-release
  image: node:10
  before_script:
    - npm install --prefix toolkit-backup
  script:
    - cd toolkit-backup && npx semantic-release -e semantic-release-monorepo
  only:
    changes:
      - toolkit-backup/**/*
    refs:
      - master

publish_toolkit-backup_docker_image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_PROJECT_NAME: "terminus7/toolkit-backup"
    README_FILEPATH: "./toolkit-backup/README.md"
  before_script:
    - apk add curl jq bash git coreutils --update
    - TAG=${CI_COMMIT_TAG#"toolkit-backup-v"}
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_PROJECT_NAME:$TAG ./toolkit-backup
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
    - ./scripts/update-dockerhub-readme.sh
  after_script:
    - docker rmi $IMAGE_PROJECT_NAME:$TAG
  only:
    - /^toolkit-backup-v\d*.\d*.\d*$/
