{{ if .Values.certManager.enable }}
# Certificate Issuer (CA)
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
name: {{ .Release.Name }}-tls-ca-issuer
spec:
  ca:
    secretName: {{ .Release.Name }}-ca-tls-secret
---
# Reference: https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls-certificate
spec:
  secretName: {{ .Release.Name }}-app-tls-secret
  dnsNames:
    - my-app.dev.local
  issuerRef:
    name: {{ .Release.Name }}-tsl-ca-issuer
    # Alternative: ClusterIssuer if there is a cluster-wide issuer available
    kind: Issuer
{{ end }}